spring.application.name=mundo-entre-libros-api

server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/mundo_entre_libros_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=mel_user
spring.datasource.password=MelPassword123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jackson.time-zone=UTC

jwt.secret=mel-super-secret-key-for-development-only-please-change-in-production-2026
jwt.expiration-ms=86400000